#include <iostream>
#include <stdlib.h>
#include <vector>
#include <algorithm>

using namespace std;

struct RandomGenerator
{
	int maxValue;
	RandomGenerator(int max) : maxValue(max) {
	}

	int operator () () {
		return rand() % maxValue;
	}
};

int main()
{
	vector<int> vecOfRandNums(10);

	// Generate 10 random numbers by lambda function
	generate(vecOfRandNums.begin(), vecOfRandNums.end(), []() {
		return rand() % 100;
		});

	cout<<"Random number generated by Lambda function"<<endl;
	for(int val : vecOfRandNums)
		cout<<val<<endl;

	// Generate 10 random numbers by functor
	generate(vecOfRandNums.begin(), vecOfRandNums.end(), 
		RandomGenerator(500));

	cout<<"Random number generated by Functor"<<endl;
	for(int val : vecOfRandNums)
		cout<<val<<endl;
	exit(0);
}
