CXX=g++
CXXFLAG=-g -I include/

# program executable name
PROG=test

all: $(PROG) 
$(PROG): stacklib
	$(CXX) src/test.cpp bin/stack.o -o bin/$(PROG) $(CXXFLAG)

stacklib:	
	$(CXX) -c src/stack.cpp -o bin/stack.o $(CXXFLAG)
#main:	
clean:
	rm -f bin/stack bin/*.o
